# site properties and page defaults
title: DSAI
subtitle: Dynamical Systems and Artificial Intelligence
description: Developing mathematically grounded AI methods to model complex dynamical systems and solve mathematical problems.
header: images/banner-image-resized_2.jpg
footer: images/banner-image-resized_4.jpg
# proofer: false

# site social media and other links
links:
  email: zahra.monfared@iwr.uni-heidelberg.de | zahra.monfared@tum.de
  orcid: 0049-0629-8713-9213
  google-scholar: citations?user=OPUIwIoAAAAJ&hl=en
  github: ZMonfared/DSAIlab.git
  twitter: Zahra__Monfared
  youtube: 

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
